version: "3.8"

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    networks:
      - bow
    volumes:
      - ./configuration/postgresql/initdb:/docker-entrypoint-initdb.d
      - postgresqldata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=root
    depends_on:
      - kea
      - bind
  app:
    build: ./webapp
    restart: unless-stopped
    networks:
      - bow
    ports:
      - 3333:3000
    depends_on:
      - postgres
    environment:
      - LORA_PROXY_TARGET=http://lora-app.darends.scouthack.com/

volumes:
  postgresqldata:

networks:
  bow:
    driver: bridge
